#!/usr/bin/env bash
# gen-stress.sh — generate a synthetic stress file for parse+check timing.
#
# Usage: tools/gen-stress.sh [N_PAIRS] [OUT]
#
# Emits N_PAIRS signature+definition pairs (so 2*N_PAIRS top-level
# declarations). Every tenth pair references the previous definition so
# the file is not trivially parallel; the rest are independent.
# Defaults: 1000 pairs (= 2000 declarations) to /tmp/stress.kp.
set -euo pipefail

n="${1:-1000}"
out="${2:-/tmp/stress.kp}"

{
  echo "-- generated by tools/gen-stress.sh: $((2 * n)) declarations"
  echo "base0 : Integer"
  echo "let base0 = 1"
  for ((i = 1; i < n; i++)); do
    echo "f$i : Integer"
    if ((i % 10 == 0)); then
      echo "let f$i = addInt f$((i - 1)) $i"
    else
      echo "let f$i = mulInt $i $((i + 1))"
    fi
  done
} >"$out"

echo "$out: $(grep -c . "$out") nonblank lines, $((2 * n)) declarations" >&2
echo "$out"
