#!/usr/bin/env bash
# gen-stress.sh — generate a synthetic stress file for parse+check timing.
#
# Usage: tools/gen-stress.sh [N_PAIRS] [OUT] [KIND]
#
# Emits N_PAIRS signature+definition pairs (so 2*N_PAIRS top-level
# declarations). Every tenth pair references the previous definition so
# the file is not trivially parallel; the rest are independent.
# KIND selects the literal family of the independent definitions:
#   int (default) | float | char — float/char exercise the lexer paths
#   that were once quadratic (multi-char lookahead per literal).
# Defaults: 1000 pairs (= 2000 declarations) to /tmp/stress.kp.
set -euo pipefail

n="${1:-1000}"
out="${2:-/tmp/stress.kp}"
kind="${3:-int}"

case "$kind" in
  int) ty=Integer ;;
  float) ty=Double ;;
  char) ty=UnicodeScalar ;;
  *)
    echo "gen-stress.sh: unknown KIND '$kind' (int|float|char)" >&2
    exit 2
    ;;
esac

{
  echo "-- generated by tools/gen-stress.sh: $((2 * n)) declarations ($kind)"
  echo "base0 : $ty"
  case "$kind" in
    int) echo "let base0 = 1" ;;
    float) echo "let base0 = 1.0" ;;
    char) echo "let base0 = 'a'" ;;
  esac
  for ((i = 1; i < n; i++)); do
    echo "f$i : $ty"
    case "$kind" in
      int)
        if ((i % 10 == 0)); then
          echo "let f$i = addInt f$((i - 1)) $i"
        else
          echo "let f$i = mulInt $i $((i + 1))"
        fi
        ;;
      float)
        if ((i % 10 == 0)); then
          echo "let f$i = f$((i - 1))"
        else
          echo "let f$i = $i.$((i % 100))e$((i % 7))"
        fi
        ;;
      char)
        if ((i % 10 == 0)); then
          echo "let f$i = f$((i - 1))"
        else
          echo "let f$i = '$(printf "\\$(printf '%03o' $((97 + i % 26)))")'"
        fi
        ;;
    esac
  done
} >"$out"

echo "$out: $(grep -c . "$out") nonblank lines, $((2 * n)) declarations" >&2
echo "$out"
