#!/usr/bin/env bash
# Run the Appendix T harness over the external black-box fixture corpus
# (another implementation's test suite) IN PLACE, and tally results.
#
# Usage: tools/run-external-fixtures.sh [FIXTURES_DIR] [RESULTS_MD] [STATS_TXT] [RAW_LOG]
#
# The raw per-fixture log (default /tmp/external-raw.log) feeds
# tools/triage-external.sh.
#
# Each fixture directory (main.kp + optional suite.ktest) is executed as
# one Appendix T directory suite by `kappa test`. Fixtures exercising
# features this implementation does not support, or using directives
# outside the portable subset, are classified `unsupported` per §T.8.
set -u

FIXTURES="${1:-/opt/workspaces/kappa/tests/Kappa.Compiler.Tests/Fixtures}"
RESULTS_MD="${2:-tests/external-results.md}"
STATS_TXT="${3:-/tmp/external-stats.txt}"
RAW_LOG="${4:-/tmp/external-raw.log}"

if [ ! -d "$FIXTURES" ]; then
  echo "fixtures directory not found: $FIXTURES" >&2
  exit 2
fi

echo "running kappa test over $FIXTURES ..." >&2
BIN="$(cabal list-bin kappa 2>/dev/null)"
if [ -z "$BIN" ]; then
  echo "kappa binary not found; run 'cabal build' first" >&2
  exit 2
fi
# One invocation per fixture directory: each is one §T.2 suite root
# (multi-file fixtures compile all their .kp files together; --suite
# forces this even when all .kp files live in subdirectories).
: >"$RAW_LOG"
for d in "$FIXTURES"/*/; do
  # kappa exits nonzero when a fixture fails, which is a normal result;
  # only synthesize a result line when none was produced (hang/crash)
  if ! timeout 60 "$BIN" test --suite "${d%/}" >>"$RAW_LOG" 2>&1; then
    if ! tail -3 "$RAW_LOG" | grep -qF "${d%/}"; then
      echo "HARNESS-ERROR ${d%/} (timeout or crash)" >>"$RAW_LOG"
    fi
  fi
done

pass=$(grep -c '^PASS '          "$RAW_LOG" || true)
fail=$(grep -c '^FAIL '          "$RAW_LOG" || true)
unsup=$(grep -c '^UNSUPPORTED '  "$RAW_LOG" || true)
herr=$(grep -c '^HARNESS-ERROR ' "$RAW_LOG" || true)
total=$((pass + fail + unsup + herr))

{
  echo "external fixtures: $FIXTURES"
  echo "date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "total: $total"
  echo "pass: $pass"
  echo "fail: $fail"
  echo "unsupported: $unsup"
  echo "harness-error: $herr"
} | tee "$STATS_TXT" >&2

{
  echo "# External fixture results"
  echo
  echo "Black-box run of \`kappa test\` over the external fixture corpus"
  echo "(\`$FIXTURES\`, a different implementation's test suite, used as"
  echo "fixtures only). Generated by \`tools/run-external-fixtures.sh\`."
  echo
  echo "| outcome | count |"
  echo "|---|---|"
  echo "| pass | $pass |"
  echo "| fail | $fail |"
  echo "| unsupported | $unsup |"
  echo "| harness error | $herr |"
  echo "| **total** | **$total** |"
  echo
  echo "## Classification rules (Appendix T)"
  echo
  echo "- **unsupported** per §T.8 covers: unmet \`requires\` preconditions"
  echo "  (§T.4 — capabilities provided: \`runTask\`, \`pipelineTrace\`; not"
  echo "  provided: \`stageDumps\`, \`incremental\`, and the nonstandard"
  echo "  \`unicodeSourceWarnings\`/\`legacyCharAlias\` names, which §T.4"
  echo "  does not list among the portable capabilities), \`x-\` extension"
  echo "  directives this harness does not support (§T.3: an unsupported"
  echo "  \`x-\` directive makes the test unsupported, never silently"
  echo "  ignored), modes and backends with no implementation here"
  echo "  (\`mode compile\`/\`mode analyze\`, \`backend\` profiles other"
  echo "  than \`interpreter\` — there are no code generators; §T.4 makes"
  echo "  unmet \`requires backend\` unsupported and \`scriptMode\` is not"
  echo "  implemented), incremental step suites (§T.7 presumes Chapter 34"
  echo "  session reuse; the \`incremental\` capability is not claimed),"
  echo "  and the structured-diagnostic/stage-dump assertions (§T.5.1"
  echo "  payload/label/related/fix/suppression, §T.5.3) whose underlying"
  echo "  record fields this implementation's diagnostics do not carry."
  echo "- **harness error** per §T.3: *\"Any unknown standard directive,"
  echo "  malformed directive, or ill-typed directive argument is a harness"
  echo "  error.\"* The corpus directives \`allow_unsafe_consume\`,"
  echo "  \`assertRunStdout\`, \`assertExecute\`, \`assertEvalErrorContains\`,"
  echo "  \`assertParameterQuantities\`, \`assertDoItemDescriptors\`,"
  echo "  \`assertInoutParameters\`, and \`assertContainsTokenTexts\` appear"
  echo "  nowhere in Appendix T (§T.4 configuration list, §T.5 assertion"
  echo "  lists) nor anywhere else in Spec.md; they are another"
  echo "  implementation's private, non-\`x-\`-prefixed directives, so the"
  echo "  spec-mandated outcome is harnessError. (\`assertEval\` and"
  echo "  \`assertDiagnosticCodes\` are likewise nonstandard but have an"
  echo "  evident portable meaning; this harness implements them as"
  echo "  documented compatibility extensions, as §T.1 permits.)"
  echo
  echo "## Unsupported, by reason"
  echo
  echo '```'
  grep '^UNSUPPORTED ' "$RAW_LOG" | sed 's/^UNSUPPORTED [^ ]* (\(.*\))$/\1/' \
    | sed 's/[0-9][0-9]*/N/g' | sort | uniq -c | sort -rn
  echo '```'
  echo
  echo "## Failures"
  echo
  echo '```'
  grep '^FAIL ' "$RAW_LOG" | sed "s|$FIXTURES/||"
  echo '```'
  echo
  echo "## Harness errors"
  echo
  echo '```'
  grep '^HARNESS-ERROR ' "$RAW_LOG" | sed "s|$FIXTURES/||"
  echo '```'
} >"$RESULTS_MD"

echo "raw log: $RAW_LOG" >&2
echo "results written to $RESULTS_MD and $STATS_TXT" >&2
