#!/usr/bin/env bash
# Run the Appendix T harness over the external black-box fixture corpus
# (another implementation's test suite) IN PLACE, and tally results.
#
# Usage: tools/run-external-fixtures.sh [FIXTURES_DIR] [RESULTS_MD] [STATS_TXT]
#
# Each fixture directory (main.kp + optional suite.ktest) is executed as
# one Appendix T directory suite by `kappa test`. Fixtures exercising
# features this implementation does not support, or using directives
# outside the portable subset, are classified `unsupported` per §T.8.
set -u

FIXTURES="${1:-/opt/workspaces/kappa/tests/Kappa.Compiler.Tests/Fixtures}"
RESULTS_MD="${2:-tests/external-results.md}"
STATS_TXT="${3:-/tmp/external-stats.txt}"
RAW_LOG="$(mktemp /tmp/external-raw.XXXXXX.log)"

if [ ! -d "$FIXTURES" ]; then
  echo "fixtures directory not found: $FIXTURES" >&2
  exit 2
fi

echo "running kappa test over $FIXTURES ..." >&2
# One process for the whole corpus: the embedded prelude is compiled once.
cabal run -v0 kappa -- test "$FIXTURES" >"$RAW_LOG" 2>&1 || true

pass=$(grep -c '^PASS '          "$RAW_LOG" || true)
fail=$(grep -c '^FAIL '          "$RAW_LOG" || true)
unsup=$(grep -c '^UNSUPPORTED '  "$RAW_LOG" || true)
herr=$(grep -c '^HARNESS-ERROR ' "$RAW_LOG" || true)
total=$((pass + fail + unsup + herr))

{
  echo "external fixtures: $FIXTURES"
  echo "date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "total: $total"
  echo "pass: $pass"
  echo "fail: $fail"
  echo "unsupported: $unsup"
  echo "harness-error: $herr"
} | tee "$STATS_TXT" >&2

{
  echo "# External fixture results"
  echo
  echo "Black-box run of \`kappa test\` over the external fixture corpus"
  echo "(\`$FIXTURES\`, a different implementation's test suite, used as"
  echo "fixtures only). Generated by \`tools/run-external-fixtures.sh\`."
  echo
  echo "| outcome | count |"
  echo "|---|---|"
  echo "| pass | $pass |"
  echo "| fail | $fail |"
  echo "| unsupported | $unsup |"
  echo "| harness error | $herr |"
  echo "| **total** | **$total** |"
  echo
  echo "## Unsupported, by reason"
  echo
  echo '```'
  grep '^UNSUPPORTED ' "$RAW_LOG" | sed 's/^UNSUPPORTED [^ ]* (\(.*\))$/\1/' \
    | sed 's/[0-9][0-9]*/N/g' | sort | uniq -c | sort -rn
  echo '```'
  echo
  echo "## Failures"
  echo
  echo '```'
  grep '^FAIL ' "$RAW_LOG" | sed "s|$FIXTURES/||"
  echo '```'
  echo
  echo "## Harness errors"
  echo
  echo '```'
  grep '^HARNESS-ERROR ' "$RAW_LOG" | sed "s|$FIXTURES/||"
  echo '```'
} >"$RESULTS_MD"

echo "raw log: $RAW_LOG" >&2
echo "results written to $RESULTS_MD and $STATS_TXT" >&2
